#  _____  _         _             _  _____                    _        
# |  __ \| |       | |           | ||  _  |                  | |       
# | |  \/| |  ___  | |__    __ _ | || | | | _   _   ___  ___ | |_  ___ 
# | | __ | | / _ \ | '_ \  / _` || || | | || | | | / _ \/ __|| __|/ __|
# | |_\ \| || (_) || |_) || (_| || |\ \/' /| |_| ||  __/\__ \| |_ \__ \
#  \____/|_| \___/ |_.__/  \__,_||_| \_/\_\ \__,_| \___||___/ \__||___/
#

############################################################
# +------------------------------------------------------+ #
# |                                                      | #
# |                     Main Settings                    | #
# |                                                      | #
# +------------------------------------------------------+ #
############################################################

quest_frenquecy: 120 # How often the quests should occur.
progressbars:
  actionbar: true # Display the progress bar on the actionbar during an active quest
  number-bars: 20 # The amount of bars
  progress-bar: '|' # What icon to use for the bars
  progress-complete: '&a'
  progress-incomplete: '&c'


############################################################
# +------------------------------------------------------+ #
# |                                                      | #
# |                      Quests                          | #
# |                                                      | #
# +------------------------------------------------------+ #
############################################################

quests:
  MiningQuest:
    type: MINING
    block: 'STONE'
    amount: 100000
    time_to_complete: 2000 # Time in seconds
    display_name: '<gradient:#82f4b1:#30c67c>Mine 100,000 Stone'
    rewards:
     - '[CONSOLE] eco give %player_name% 500'
     - '[SOUND] ENTITY_VILLAGER_YES'
     - '[ACTIONBAR] <gradient:#82f4b1:#30c67c>QUEST COMPLETED'
     - '[TITLE] &2&lQUEST<n>&aCompleted'
     - '[TOAST:DIAMOND] Quest Completed<n>You completed the quest'

  EXPQuest:
    type: EXP
    amount: 100000
    time_to_complete: 2000 
    display_name: '<gradient:#82f4b1:#30c67c>Collect 100,000 EXP'
    rewards:
     - '[CONSOLE] eco give %player_name% 500'
     - '[SOUND] ENTITY_VILLAGER_YES'
     - '[ACTIONBAR] <gradient:#82f4b1:#30c67c>QUEST COMPLETED'
     - '[TITLE] &2&lQUEST<n>&aCompleted'
     - '[TOAST:DIAMOND] Quest Completed<n>You completed the quest'
     
  MOBQuest:
    type: MOB
    mob: 'ZOMBIE'
    amount: 150
    time_to_complete: 2000 
    display_name: '<gradient:#82f4b1:#30c67c>Kill 150 Zombies'
    rewards:
     - '[CONSOLE] eco give %player_name% 500'
     - '[SOUND] ENTITY_VILLAGER_YES'
     - '[ACTIONBAR] <gradient:#82f4b1:#30c67c>QUEST COMPLETED'
     - '[TITLE] &2&lQUEST<n>&aCompleted'
     - '[TOAST:DIAMOND] Quest Completed<n>You completed the quest'

  FishingQuest:
    type: FISHING
    item: 'COD'
    amount: 200
    time_to_complete: 2000 
    display_name: '<gradient:#42a5f5:#0d47a1>Catch 200 Cod'
    rewards:
     - '[CONSOLE] eco give %player_name% 400'
     - '[SOUND] ENTITY_FISHING_BOBBER_RETRIEVE'
     - '[ACTIONBAR] <gradient:#42a5f5:#0d47a1>QUEST COMPLETED'
     - '[TITLE] &3&lQUEST<n>&bCompleted'
     - '[TOAST:FISH] Quest Completed<n>You completed the quest'
  SmeltingQuest:
    type: SMELTING
    item: 'IRON_INGOT'
    amount: 1000
    time_to_complete: 2000 
    display_name: '<gradient:#d4af37:#b8860b>Smelt 1,000 Iron Ingots'
    rewards:
     - '[CONSOLE] eco give %player_name% 500'
     - '[SOUND] BLOCK_FURNACE_USE'
     - '[ACTIONBAR] <gradient:#d4af37:#b8860b>QUEST COMPLETED'
     - '[TITLE] &e&lQUEST<n>&aCompleted'
     - '[TOAST:IRON_INGOT] Quest Completed<n>You completed the quest'

  CraftingQuest:
    type: CRAFTING
    item: 'DIAMOND_SWORD'
    amount: 50
    time_to_complete: 2000 
    display_name: '<gradient:#00ced1:#4682b4>Craft 50 Diamond Swords'
    rewards:
     - '[CONSOLE] eco give %player_name% 800'
     - '[SOUND] ENTITY_PLAYER_LEVELUP'
     - '[ACTIONBAR] <gradient:#00ced1:#4682b4>QUEST COMPLETED'
     - '[TITLE] &b&lQUEST<n>&aCompleted'
     - '[TOAST:DIAMOND_SWORD] Quest Completed<n>You completed the quest'
